# Generated by Django 5.2.16 on 2026-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code_body', models.TextField()),
                ('language', models.CharField(default='bash', max_length=50)),
                ('tags', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='snippets_sn_title_2486e2_idx'), models.Index(fields=['tags'], name='snippets_sn_tags_d35868_idx')],
            },
        ),
    ]